version: "3"
services:
  phonebookfe:
    build: ./viteclient/phonebookfe
    container_name: phonebookfe
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - phonebookbe
  phonebookbe:
    env_file: .env
    build: ./server
    container_name: phonebookbe
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PW: ${MONGODB_PW}
      USPS_USERID: ${USPS_USERID}
    restart: always
    ports:
      - 8000:8000
