version: "3"
services:
  phonebookfe:
    build: ./viteclient/phonebookfe
    container_name: phonebookfe
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - phonebookbe
  phonebookbe:
    build: ./server
    container_name: phonebookbe
    restart: always
    ports:
      - 5000:5000
